#!/usr/bin/env python

from bugzilla.agents import BMOAgent
import subprocess

if __name__ == '__main__':
    username = subprocess.check_output('git config user.email', shell=True)
    bmo = BMOAgent(username, None)

    options = {
        'email1':             username,
        'email1_assigned_to': 1,
        'status':             'NEW'
    }

    buglist = bmo.get_bug_list(options)
    print "Found %s bugs" % (len(buglist))
    for bug in buglist:
        print bug
